const file=document.querySelector('#file'),stage=document.querySelector('#stage'),pick=document.querySelector('#pick'),editbar=document.querySelector('#editbar');let image=null,selected=null,photoRotation=0,photoFlip=false;
const stickers=['⭐','❤️','✨','🔥','💫','🌈','☀️','🌙','🦋','🌸','🍀','🎀','😎','🥹','😂','🤍','💜','🩵','🍓','🍋','🍒','🌿','🪩','🎧'];
const fonts=['Inter','Arial','Georgia','Times New Roman','Courier New','Impact','Trebuchet MS','Verdana','Palatino Linotype','Comic Sans MS','Brush Script MT','serif','sans-serif','monospace'];
const colors=['#fff','#000','#ff3b30','#ff9500','#ffcc00','#34c759','#00c7be','#007aff','#5856d6','#af52de','#ff2d55'];
const filters={Normal:'none',Vivid:'saturate(1.45) contrast(1.08)',Warm:'saturate(1.15) sepia(.18)',Cool:'saturate(1.1) hue-rotate(12deg)',Mono:'grayscale(1)',Fade:'saturate(.7) contrast(.9) brightness(1.08)',Dramatic:'contrast(1.3) saturate(1.2)'};
let textColor='#fff',bgColor='#fff',bgOn=false,currentFilter='Normal';
function openFile(){file.click()}pick?.addEventListener('click',openFile);document.querySelector('#gallery').onclick=openFile;file.onchange=e=>{const f=e.target.files?.[0];if(f)loadImage(URL.createObjectURL(f))};
function loadImage(url){stage.innerHTML=`<img id="photo" src="${url}" alt="Selected photo"><div id="overlays"></div><div class="watermark">made with intensed-dev.github.io/paperplane</div>`;image=document.querySelector('#photo');document.querySelector('#closeBtn').classList.remove('hidden');document.querySelector('#backBtn').classList.remove('hidden');photoRotation=0;photoFlip=false;image.onload=fitStage}
function fitStage(){stage.style.aspectRatio=`${image.naturalWidth}/${image.naturalHeight}`}
function closeSheets(){document.querySelectorAll('.sheet').forEach(x=>x.classList.remove('open'))}
function selectOverlay(el){if(selected)selected.classList.remove('selected');selected=el;el.classList.add('selected');editbar.classList.add('open')}
function addOverlay(value,kind,o={}){if(!image)return;const el=document.createElement('div');el.className=`overlay ${kind}`;el.textContent=value;el.style.left='50%';el.style.top='50%';el.dataset.x=.5;el.dataset.y=.5;el.dataset.scale=o.scale||1;el.dataset.rot=o.rot||0;el.style.setProperty('--scale',el.dataset.scale);el.style.setProperty('--rot',el.dataset.rot+'deg');if(kind==='text'){el.dataset.font=o.font||'Inter';el.dataset.color=o.color||'#fff';el.dataset.bg=o.bg||'';renderText(el)}document.querySelector('#overlays').append(el);selectOverlay(el);attachGestures(el)}
function renderText(el){el.style.fontFamily=`"${el.dataset.font}"`;el.style.color=el.dataset.color;if(el.dataset.bg){el.style.background=el.dataset.bg;el.style.color=el.dataset.bg==='#000'?'#fff':'#000';el.style.padding='6px 10px';el.style.borderRadius='8px'}else{el.style.background='transparent';el.style.padding='0';el.style.borderRadius='0'}}
function attachGestures(el){let dragging=false,sx=0,sy=0,startX=0,startY=0,pts=new Map(),pinch=false,startDist=0,startScale=1,startAngle=0,startRot=0;
el.addEventListener('pointerdown',e=>{e.stopPropagation();selectOverlay(el);if(pts.size===0){el.setPointerCapture(e.pointerId);dragging=true;sx=e.clientX;sy=e.clientY;startX=el.offsetLeft;startY=el.offsetTop}pts.set(e.pointerId,{clientX:e.clientX,clientY:e.clientY});if(pts.size===2){dragging=false;const a=[...pts.values()];startDist=Math.hypot(a[0].clientX-a[1].clientX,a[0].clientY-a[1].clientY);startAngle=Math.atan2(a[1].clientY-a[0].clientY,a[1].clientX-a[0].clientX);startScale=+el.dataset.scale;startRot=+el.dataset.rot;pinch=true}});
el.addEventListener('pointermove',e=>{if(pts.has(e.pointerId))pts.set(e.pointerId,{clientX:e.clientX,clientY:e.clientY});if(pts.size===2){const a=[...pts.values()];const dist=Math.hypot(a[0].clientX-a[1].clientX,a[0].clientY-a[1].clientY),angle=Math.atan2(a[1].clientY-a[0].clientY,a[1].clientX-a[0].clientX);el.dataset.scale=Math.max(.25,Math.min(5,startScale*dist/startDist));el.dataset.rot=startRot+(angle-startAngle)*180/Math.PI;el.style.setProperty('--scale',el.dataset.scale);el.style.setProperty('--rot',el.dataset.rot+'deg');return}if(dragging){el.style.left=startX+e.clientX-sx+'px';el.style.top=startY+e.clientY-sy+'px'}});
const end=e=>{pts.delete(e.pointerId);if(pts.size<2){pinch=false;dragging=false}};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('dblclick',()=>{if(el.classList.contains('text'))openTextEditor(el);else removeOverlay(el)})}
function removeOverlay(el){if(selected===el){selected=null;editbar.classList.remove('open')}el.remove()}
function openTextEditor(el){selected=el;document.querySelector('#textSheetTitle').textContent='Edit text';document.querySelector('#textInput').value=el.textContent;document.querySelector('#fontGrid').querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.font===el.dataset.font));textColor=el.dataset.color||'#fff';bgOn=!!el.dataset.bg;bgColor=el.dataset.bg||'#fff';document.querySelector('#bgToggle').classList.toggle('on',bgOn);document.querySelector('#bgOptions').classList.toggle('hidden',!bgOn);document.querySelector('#textConfirm').textContent='Save changes';document.querySelector('#textSheet').classList.add('open')}
function rotate(d){if(!selected)return;const r=+selected.dataset.rot+d;selected.dataset.rot=r;selected.style.setProperty('--rot',r+'deg')}
const sg=document.querySelector('#stickerGrid');stickers.forEach(s=>{const b=document.createElement('button');b.className='sticker';b.textContent=s;b.setAttribute('aria-label',`Add ${s}`);b.onclick=()=>{addOverlay(s,'sticker');closeSheets()};sg.append(b)});
const fg=document.querySelector('#fontGrid');fonts.forEach(f=>{const b=document.createElement('button');b.className='font-btn';b.textContent=f;b.dataset.font=f;b.style.fontFamily=`"${f}"`;b.onclick=()=>{textColor=textColor||'#fff';fg.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')};fg.append(b)});
function makeSwatches(root,arr,cb){arr.forEach(c=>{const b=document.createElement('button');b.className='swatch';b.style.background=c;b.dataset.color=c;b.onclick=()=>{root.querySelectorAll('.swatch').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');cb(c)};root.append(b)})}makeSwatches(document.querySelector('#textColors'),colors,c=>textColor=c);makeSwatches(document.querySelector('#bgColors'),['#fff','#000','#ff3b30','#ff9500','#34c759','#007aff','#5856d6','#af52de'],c=>bgColor=c);
document.querySelector('#bgToggle').onclick=e=>{bgOn=!bgOn;e.currentTarget.classList.toggle('on',bgOn);document.querySelector('#bgOptions').classList.toggle('hidden',!bgOn)};
document.querySelector('#stickers').onclick=()=>{closeSheets();document.querySelector('#stickerSheet').classList.add('open')};
document.querySelector('#addText').onclick=()=>{closeSheets();selected=null;document.querySelector('#textSheetTitle').textContent='Text';document.querySelector('#textInput').value='';document.querySelector('#textConfirm').textContent='Add text';document.querySelector('#textSheet').classList.add('open');document.querySelector('#textInput').focus()};
document.querySelector('#textConfirm').onclick=()=>{const v=document.querySelector('#textInput').value.trim();if(!v)return;const font=document.querySelector('.font-btn.selected')?.dataset.font||'Inter';if(selected&&selected.classList.contains('text')){selected.textContent=v;selected.dataset.font=font;selected.dataset.color=textColor;selected.dataset.bg=bgOn?bgColor:'';renderText(selected)}else addOverlay(v,'text',{font,color:textColor,bg:bgOn?bgColor:''});selected=null;editbar.classList.remove('open');document.querySelector('#textInput').value='';document.querySelector('#textConfirm').textContent='Add text';document.querySelector('#textSheetTitle').textContent='Text';closeSheets()};
document.querySelector('#editOverlay').onclick=()=>selected?.classList.contains('text')&&openTextEditor(selected);document.querySelector('#deleteOverlay').onclick=()=>selected&&removeOverlay(selected);document.querySelector('#rotateLeft').onclick=()=>rotate(-15);document.querySelector('#rotateRight').onclick=()=>rotate(15);document.querySelector('#closeBtn').onclick=()=>location.reload();document.querySelector('#backBtn').onclick=()=>{if(selected){selected.classList.remove('selected');selected=null;editbar.classList.remove('open')}};document.addEventListener('pointerdown',e=>{if(!e.target.closest('.overlay')&&!e.target.closest('.editbar')){if(selected)selected.classList.remove('selected');selected=null;editbar.classList.remove('open')}});
const filterGrid=document.querySelector('#filterGrid');Object.entries(filters).forEach(([name,filter])=>{const b=document.createElement('button');b.className='filter-btn';b.textContent=name;b.onclick=()=>{currentFilter=name;image.style.filter=filter;filterGrid.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')};filterGrid.append(b)});filterGrid.firstChild?.classList.add('selected');
function range(id,out,unit=''){const r=document.querySelector('#'+id),o=document.querySelector('#'+out);r.oninput=()=>{o.value=r.value+unit;applyAdjust()};o.value=r.value+unit}function applyAdjust(){if(!image)return;image.style.filter=`${filters[currentFilter]} brightness(${document.querySelector('#brightness').value}%) contrast(${document.querySelector('#contrast').value}%) saturate(${document.querySelector('#saturation').value}%) blur(${document.querySelector('#blur').value}px)`;image.style.transform=`rotate(${photoRotation}deg) scaleX(${photoFlip?-1:1})`};['brightness','contrast','saturation','blur'].forEach((x)=>range(x,x+'Out',x==='blur'?'px':'%'));
document.querySelector('#adjust').onclick=()=>{if(!image)return;closeSheets();document.querySelector('#adjustSheet').classList.add('open')};document.querySelector('#rotatePhoto').onclick=()=>{photoRotation=(photoRotation+90)%360;applyAdjust()};document.querySelector('#flipPhoto').onclick=()=>{photoFlip=!photoFlip;applyAdjust()};document.querySelector('#resetAdjust').onclick=()=>{photoRotation=0;photoFlip=false;currentFilter='Normal';['brightness','contrast','saturation'].forEach(x=>document.querySelector('#'+x).value=100);document.querySelector('#blur').value=0;document.querySelector('#'+('brightnessOut')).value='100%';document.querySelector('#contrastOut').value='100%';document.querySelector('#saturationOut').value='100%';document.querySelector('#blurOut').value='0px';image.style.filter='none';image.style.transform='none'};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeSheets);
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function drawFilter(ctx,filter){return filter==='none'?null:filter}
async function exportImage(){if(!image)return alert('Add a photo first.');const max=2400,scale=Math.min(1,max/image.naturalWidth),w=Math.round(image.naturalWidth*scale),h=Math.round(image.naturalHeight*scale),footer=64;const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h+footer;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.save();ctx.translate(w/2,h/2);ctx.rotate(photoRotation*Math.PI/180);ctx.scale(photoFlip?-1:1,1);ctx.filter=`${filters[currentFilter]} brightness(${document.querySelector('#brightness').value}%) contrast(${document.querySelector('#contrast').value}%) saturate(${document.querySelector('#saturation').value}%) blur(${document.querySelector('#blur').value}px)`;const rw=photoRotation%180===0?w:h,rh=photoRotation%180===0?h:w;ctx.drawImage(image,-rw/2,-rh/2,rw,rh);ctx.restore();const sr=stage.getBoundingClientRect(),ir=image.getBoundingClientRect(),overlays=[...document.querySelectorAll('.overlay')];for(const o of overlays){const x=(o.offsetLeft-(ir.left-sr.left))*scale,y=(o.offsetTop-(ir.top-sr.top))*scale,s=+o.dataset.scale||1,r=(+o.dataset.rot||0)*Math.PI/180;ctx.save();ctx.translate(x,y);ctx.rotate(r);ctx.scale(s,s);ctx.textAlign='center';ctx.textBaseline='middle';if(o.classList.contains('text')){await document.fonts.load(`32px "${o.dataset.font}"`);ctx.font=`750 32px "${o.dataset.font}"`;const m=ctx.measureText(o.textContent),padX=10,padY=6;if(o.dataset.bg){ctx.fillStyle=o.dataset.bg;roundRect(ctx,-m.width/2-padX,-16-padY,m.width+padX*2,32+padY*2,8);ctx.fill()}ctx.fillStyle=o.dataset.bg?(o.dataset.bg==='#000'?'#fff':'#000'):(o.dataset.color||'#fff');ctx.shadowColor='rgba(0,0,0,.55)';ctx.shadowBlur=6;ctx.fillText(o.textContent,0,0)}else{ctx.font='48px sans-serif';ctx.shadowColor='transparent';ctx.fillText(o.textContent,0,0)}ctx.restore()}ctx.fillStyle='#fff';ctx.fillRect(0,h,w,footer);ctx.fillStyle='#111';ctx.font='700 18px -apple-system,BlinkMacSystemFont,"SF Pro Display",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('made with intensed-dev.github.io/paperplane',w/2,h+footer/2);canvas.toBlob(blob=>{const a=document.createElement('a');a.download='paperplane.png';a.href=URL.createObjectURL(blob);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')}
document.querySelector('#download').onclick=exportImage;
