const file=$('#file'),stage=$('#stage'),editbar=$('#editbar'),toast=$('#toast');let image=null,selected=null,photoRotation=0,photoFlip=false,currentFilter='Normal',history=[],historyIndex=-1;textColor='#fff',bgColor='#fff',bgOn=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const stickers=[['⭐','star'],['❤️','heart love'],['✨','sparkle'],['🔥','fire'],['💫','star'],['🌈','rainbow'],['☀️','sun'],['🌙','moon'],['🦋','butterfly'],['🌸','flower'],['🍀','clover'],['🎀','bow'],['😎','cool'],['🥹','cry'],['😂','laugh'],['🤍','white heart'],['💜','purple heart'],['🩵','blue heart'],['🍓','strawberry'],['🍋','lemon'],['🍒','cherry'],['🌿','leaf'],['🪩','disco'],['🎧','music'],['🎉','party'],['💎','diamond'],['☁️','cloud'],['🌻','sunflower'],['🐝','bee'],['🐸','frog'],['🐱','cat'],['🐶','dog'],['👑','crown'],['💖','pink heart'],['💯','hundred']];
const fonts=['Inter','Arial','Helvetica','Georgia','Times New Roman','Courier New','Impact','Trebuchet MS','Verdana','Palatino Linotype','Comic Sans MS','Brush Script MT','serif','sans-serif','monospace'];
const colors=['#fff','#000','#ff3b30','#ff9500','#ffcc00','#34c759','#00c7be','#007aff','#5856d6','#af52de','#ff2d55'];
const filters={Normal:'none',Vivid:'saturate(1.45) contrast(1.08)',Warm:'saturate(1.15) sepia(.18)',Cool:'saturate(1.1) hue-rotate(12deg)',Mono:'grayscale(1)',Fade:'saturate(.7) contrast(.9) brightness(1.08)',Dramatic:'contrast(1.3) saturate(1.2)',Noir:'grayscale(1) contrast(1.35)',Vintage:'sepia(.35) saturate(.8) contrast(.95)'};
function toastMsg(t){toast.textContent=t;toast.classList.add('show');clearTimeout(toastMsg.t);toastMsg.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function openFile(){file.click()}$('#pick')?.addEventListener('click',openFile);$('#gallery').onclick=openFile;file.onchange=e=>{const f=e.target.files?.[0];if(f){loadImage(URL.createObjectURL(f));file.value=''}};
function loadImage(url){stage.innerHTML=`<img id="photo" src="${url}" alt="Selected photo"><div id="overlays"></div><div class="watermark">made with intensed-dev.github.io/paperplane</div>`;image=$('#photo');$('#closeBtn').classList.remove('hidden');$('#backBtn').classList.remove('hidden');photoRotation=0;photoFlip=false;history=[];historyIndex=-1;image.onload=()=>{fitStage();renderPhoto();saveHistory()}}
function fitStage(){if(image)stage.style.aspectRatio=`${image.naturalWidth}/${image.naturalHeight}`}
function closeSheets(){$$('.sheet').forEach(x=>x.classList.remove('open'))}
function selectOverlay(el){if(selected&&selected!==el)selected.classList.remove('selected');selected=el;if(el){el.classList.add('selected');editbar.classList.add('open')}else editbar.classList.remove('open')}
function addOverlay(value,kind,o={}){if(!image)return;const el=document.createElement('div');el.className=`overlay ${kind}`;el.textContent=value;el.dataset.x=o.x??.5;el.dataset.y=o.y??.5;el.dataset.scale=o.scale||1;el.dataset.rot=o.rot||0;el.style.left=`${el.dataset.x*100}%`;el.style.top=`${el.dataset.y*100}%`;el.style.setProperty('--scale',el.dataset.scale);el.style.setProperty('--rot',`${el.dataset.rot}deg`);if(kind==='text'){el.dataset.font=o.font||'Inter';el.dataset.color=o.color||'#fff';el.dataset.bg=o.bg||'';el.dataset.size=o.size||100;el.dataset.opacity=o.opacity||100;el.dataset.bold=o.bold??true;el.dataset.italic=o.italic??false;el.dataset.shadow=o.shadow??true;renderText(el)}$('#overlays').append(el);selectOverlay(el);attachGestures(el);saveHistory()}
function renderText(el){el.style.fontFamily=`"${el.dataset.font}"`;el.style.color=el.dataset.bg?(el.dataset.bg==='#000'?'#fff':'#000'):(el.dataset.color||'#fff');el.style.background=el.dataset.bg||'transparent';el.style.padding=el.dataset.bg?'7px 11px':'0';el.style.borderRadius=el.dataset.bg?'9px':'0';el.style.fontSize=`${32*(+el.dataset.size||100)/100}px`;el.style.fontWeight=el.dataset.bold==='false'?'400':'700';el.style.fontStyle=el.dataset.italic==='true'?'italic':'normal';el.style.opacity=(+el.dataset.opacity||100)/100;el.style.textShadow=el.dataset.shadow==='false'?'none':'0 2px 7px rgba(0,0,0,.5)'}
function setOverlayPosition(el,x,y){el.dataset.x=Math.max(0,Math.min(1,x));el.dataset.y=Math.max(0,Math.min(1,y));el.style.left=`${el.dataset.x*100}%`;el.style.top=`${el.dataset.y*100}%`}
function attachGestures(el){let pts=new Map(),drag=false,start=null,pinch=null;el.addEventListener('pointerdown',e=>{e.stopPropagation();selectOverlay(el);pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===1){const r=$('#overlays').getBoundingClientRect();start={x:e.clientX,y:e.clientY,px:+el.dataset.x*r.width,py:+el.dataset.y*r.height};drag=true}if(pts.size===2){drag=false;const a=[...pts.values()];pinch={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),angle:Math.atan2(a[1].y-a[0].y,a[1].x-a[0].x),scale:+el.dataset.scale,rot:+el.dataset.rot}});el.addEventListener('pointermove',e=>{if(!pts.has(e.pointerId))return;pts.set(e.pointerId,{x:e.clientX,y:e.clientY});const r=$('#overlays').getBoundingClientRect();if(pts.size===2&&pinch){const a=[...pts.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),angle=Math.atan2(a[1].y-a[0].y,a[1].x-a[0].x);el.dataset.scale=Math.max(.2,Math.min(8,pinch.scale*dist/pinch.dist));el.dataset.rot=pinch.rot+(angle-pinch.angle)*180/Math.PI;el.style.setProperty('--scale',el.dataset.scale);el.style.setProperty('--rot',`${el.dataset.rot}deg`);return}if(drag&&pts.size===1)setOverlayPosition(el,(start.px+e.clientX-start.x)/r.width,(start.py+e.clientY-start.y)/r.height)});const end=e=>{pts.delete(e.pointerId);if(pts.size<2)pinch=null;if(!pts.size){drag=false;saveHistory()}};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('dblclick',()=>el.classList.contains('text')?openTextEditor(el):removeOverlay(el))}
function removeOverlay(el){if(!el)return;el.remove();if(selected===el)selectOverlay(null);saveHistory()}
function openTextEditor(el){selected=el;$('#textSheetTitle').textContent='Edit text';$('#textInput').value=el.textContent;$$('#fontGrid button').forEach(b=>b.classList.toggle('selected',b.dataset.font===el.dataset.font));textColor=el.dataset.color||'#fff';bgOn=!!el.dataset.bg;bgColor=el.dataset.bg||'#fff';$('#bgToggle').classList.toggle('on',bgOn);$('#bgOptions').classList.toggle('hidden',!bgOn);$('#textSize').value=el.dataset.size||100;$('#textSizeOut').value=`${el.dataset.size||100}%`;$('#textOpacity').value=el.dataset.opacity||100;$('#textOpacityOut').value=`${el.dataset.opacity||100}%`;$('#textBold').classList.toggle('active',el.dataset.bold!=='false');$('#textItalic').classList.toggle('active',el.dataset.italic==='true');$('#textShadow').classList.toggle('active',el.dataset.shadow!=='false');$('#textConfirm').textContent='Save changes';$('#textSheet').classList.add('open');$('#textInput').focus()}
function rotate(d){if(!selected)return;selected.dataset.rot=+selected.dataset.rot+d;selected.style.setProperty('--rot',`${selected.dataset.rot}deg`);saveHistory()}
function renderStickers(list=stickers){const q=($('#stickerSearch').value||'').toLowerCase();$('#stickerGrid').innerHTML='';list.filter(x=>!q||x[0].includes(q)||x[1].includes(q)).forEach(([s])=>{const b=document.createElement('button');b.className='sticker';b.textContent=s;b.setAttribute('aria-label',`Add ${s}`);b.onclick=()=>{addOverlay(s,'sticker');closeSheets()};$('#stickerGrid').append(b)})}renderStickers();$('#stickerSearch').oninput=()=>renderStickers();
const fg=$('#fontGrid');fonts.forEach(f=>{const b=document.createElement('button');b.className='font-btn';b.textContent=f;b.dataset.font=f;b.style.fontFamily=`"${f}"`;b.onclick=()=>{fg.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');if(selected?.classList.contains('text')){selected.dataset.font=f;renderText(selected);saveHistory()}};fg.append(b)});
function makeSwatches(root,arr,cb){arr.forEach(c=>{const b=document.createElement('button');b.className='swatch';b.style.background=c;b.dataset.color=c;b.onclick=()=>{root.querySelectorAll('.swatch').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');cb(c);if(selected?.classList.contains('text')){selected.dataset.color=textColor;selected.dataset.bg=bgOn?bgColor:'';renderText(selected);saveHistory()}};root.append(b)})}makeSwatches($('#textColors'),colors,c=>textColor=c);makeSwatches($('#bgColors'),['#fff','#000','#ff3b30','#ff9500','#34c759','#007aff','#5856d6','#af52de'],c=>bgColor=c);
$('#bgToggle').onclick=e=>{bgOn=!bgOn;e.currentTarget.classList.toggle('on',bgOn);$('#bgOptions').classList.toggle('hidden',!bgOn)};$('#stickers').onclick=()=>{closeSheets();$('#stickerSheet').classList.add('open');$('#stickerSearch').focus()};
$('#addText').onclick=()=>{closeSheets();selectOverlay(null);$('#textSheetTitle').textContent='Text';$('#textInput').value='';$('#textSize').value=100;$('#textSizeOut').value='100%';$('#textOpacity').value=100;$('#textOpacityOut').value='100%';$('#textBold').classList.add('active');$('#textItalic').classList.remove('active');$('#textShadow').classList.add('active');$('#textConfirm').textContent='Add text';$('#textSheet').classList.add('open');$('#textInput').focus()};
function updateTextStyle(){if(!selected?.classList.contains('text'))return;selected.dataset.size=$('#textSize').value;selected.dataset.opacity=$('#textOpacity').value;selected.dataset.bold=$('#textBold').classList.contains('active');selected.dataset.italic=$('#textItalic').classList.contains('active');selected.dataset.shadow=$('#textShadow').classList.contains('active');renderText(selected)}
$('#textSize').oninput=()=>{$('#textSizeOut').value=`${$('#textSize').value}%`;updateTextStyle()};$('#textOpacity').oninput=()=>{$('#textOpacityOut').value=`${$('#textOpacity').value}%`;updateTextStyle()};['textBold','textItalic','textShadow'].forEach(id=>$('#'+id).onclick=()=>{$('#'+id).classList.toggle('active');updateTextStyle()});
$('#textConfirm').onclick=()=>{const v=$('#textInput').value.trim();if(!v)return;const font=$('#fontGrid .selected')?.dataset.font||'Inter';if(selected?.classList.contains('text')){selected.textContent=v;selected.dataset.font=font;selected.dataset.color=textColor;selected.dataset.bg=bgOn?bgColor:'';updateTextStyle();renderText(selected);saveHistory()}else addOverlay(v,'text',{font,color:textColor,bg:bgOn?bgColor:'',size:$('#textSize').value,opacity:$('#textOpacity').value,bold:$('#textBold').classList.contains('active'),italic:$('#textItalic').classList.contains('active'),shadow:$('#textShadow').classList.contains('active')});selectOverlay(null);closeSheets()};
$('#editOverlay').onclick=()=>selected?.classList.contains('text')&&openTextEditor(selected);$('#deleteOverlay').onclick=()=>selected&&removeOverlay(selected);$('#rotateLeft').onclick=()=>rotate(-15);$('#rotateRight').onclick=()=>rotate(15);$('#closeBtn').onclick=()=>location.reload();$('#backBtn').onclick=()=>selectOverlay(null);document.addEventListener('pointerdown',e=>{if(!e.target.closest('.overlay')&&!e.target.closest('.editbar')&&!e.target.closest('.sheet'))selectOverlay(null)});
const filterGrid=$('#filterGrid');Object.entries(filters).forEach(([name,filter])=>{const b=document.createElement('button');b.className='filter-btn';b.textContent=name;b.onclick=()=>{currentFilter=name;renderPhoto();filterGrid.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');saveHistory()};filterGrid.append(b)});filterGrid.firstChild?.classList.add('selected');
function range(id,out,unit=''){const r=$('#'+id),o=$('#'+out);r.oninput=()=>{o.value=r.value+unit;renderPhoto()};o.value=r.value+unit}['brightness','contrast','saturation','blur'].forEach(x=>range(x,x+'Out',x==='blur'?'px':'%'));
function renderPhoto(){if(!image)return;image.style.filter=`${filters[currentFilter]} brightness(${$('#brightness').value}%) contrast(${$('#contrast').value}%) saturate(${$('#saturation').value}%) blur(${$('#blur').value}px)`;image.style.transform=`rotate(${photoRotation}deg) scaleX(${photoFlip?-1:1})`}
$('#adjust').onclick=()=>{if(!image)return;closeSheets();$('#adjustSheet').classList.add('open')};$('#rotatePhoto').onclick=()=>{photoRotation=(photoRotation+90)%360;renderPhoto();saveHistory()};$('#flipPhoto').onclick=()=>{photoFlip=!photoFlip;renderPhoto();saveHistory()};$('#resetAdjust').onclick=()=>{photoRotation=0;photoFlip=false;currentFilter='Normal';['brightness','contrast','saturation'].forEach(x=>$('#'+x).value=100);$('#blur').value=0;$('#brightnessOut').value='100%';$('#contrastOut').value='100%';$('#saturationOut').value='100%';$('#blurOut').value='0px';renderPhoto();saveHistory()};$$('[data-close]').forEach(b=>b.onclick=closeSheets);
function snapshot(){return JSON.stringify({rotation:photoRotation,flip:photoFlip,filter:currentFilter,brightness:$('#brightness').value,contrast:$('#contrast').value,saturation:$('#saturation').value,blur:$('#blur').value,overlays:$$('.overlay').map(o=>({kind:o.classList.contains('text')?'text':'sticker',value:o.textContent,x:o.dataset.x,y:o.dataset.y,scale:o.dataset.scale,rot:o.dataset.rot,font:o.dataset.font,color:o.dataset.color,bg:o.dataset.bg,size:o.dataset.size,opacity:o.dataset.opacity,bold:o.dataset.bold,italic:o.dataset.italic,shadow:o.dataset.shadow}))})}
function saveHistory(){if(!image)return;const s=snapshot();if(history[historyIndex]===s)return;history=history.slice(0,historyIndex+1);history.push(s);historyIndex=history.length-1;updateHistoryButtons()}function restore(s){const d=JSON.parse(s);photoRotation=d.rotation;photoFlip=d.flip;currentFilter=d.filter;$('#brightness').value=d.brightness;$('#contrast').value=d.contrast;$('#saturation').value=d.saturation;$('#blur').value=d.blur;$('#brightnessOut').value=d.brightness+'%';$('#contrastOut').value=d.contrast+'%';$('#saturationOut').value=d.saturation+'%';$('#blurOut').value=d.blur+'px';$('#overlays').innerHTML='';d.overlays.forEach(o=>addOverlay(o.value,o.kind,{x:+o.x,y:+o.y,scale:+o.scale,rot:+o.rot,font:o.font,color:o.color,bg:o.bg,size:o.size,opacity:o.opacity,bold:o.bold,italic:o.italic,shadow:o.shadow}));selectOverlay(null);renderPhoto();$$('#filterGrid button').forEach(b=>b.classList.toggle('selected',b.textContent===currentFilter))}function undo(){if(historyIndex<=0)return;historyIndex--;restore(history[historyIndex]);updateHistoryButtons()}function redo(){if(historyIndex>=history.length-1)return;historyIndex++;restore(history[historyIndex]);updateHistoryButtons()}function updateHistoryButtons(){if($('#undoBtn'))$('#undoBtn').disabled=historyIndex<=0;if($('#redoBtn'))$('#redoBtn').disabled=historyIndex>=history.length-1}$('#undoBtn')?.addEventListener('click',undo);$('#redoBtn')?.addEventListener('click',redo);
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
async function exportImage(){if(!image)return alert('Add a photo first.');const maxSide=3000,nw=image.naturalWidth,nh=image.naturalHeight,baseScale=Math.min(1,maxSide/Math.max(nw,nh)),outW=Math.round(nw*baseScale),outH=Math.round(nh*baseScale),footer=Math.max(96,Math.round(outW*.04));const canvas=document.createElement('canvas');canvas.width=outW;canvas.height=outH+footer;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.save();ctx.translate(outW/2,outH/2);ctx.rotate(photoRotation*Math.PI/180);ctx.scale(photoFlip?-1:1,1);ctx.filter=`${filters[currentFilter]} brightness(${$('#brightness').value}%) contrast(${$('#contrast').value}%) saturate(${$('#saturation').value}%) blur(${$('#blur').value}px)`;ctx.drawImage(image,-outW/2,-outH/2,outW,outH);ctx.restore();
const imageRect=image.getBoundingClientRect(),naturalRatioX=outW/imageRect.width,naturalRatioY=outH/imageRect.height;for(const o of $$('.overlay')){const r=o.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,p={x:(cx-imageRect.left)/imageRect.width,y:(cy-imageRect.top)/imageRect.height},s=+o.dataset.scale||1,rot=(+o.dataset.rot||0)*Math.PI/180;ctx.save();ctx.translate(p.x*outW,p.y*outH);ctx.rotate(rot);ctx.scale(s*naturalRatioX,s*naturalRatioY);ctx.textAlign='center';ctx.textBaseline='middle';if(o.classList.contains('text')){const font=o.dataset.font||'Inter',size=32*(+o.dataset.size||100)/100;await document.fonts.load(`${o.dataset.italic==='true'?'italic ':''}${o.dataset.bold!=='false'?'700':'400'} ${size}px "${font}"`);ctx.font=`${o.dataset.italic==='true'?'italic ':''}${o.dataset.bold!=='false'?'700':'400'} ${size}px "${font}"`;ctx.globalAlpha=(+o.dataset.opacity||100)/100;const m=ctx.measureText(o.textContent),padX=11,padY=7;if(o.dataset.bg){ctx.fillStyle=o.dataset.bg;roundRect(ctx,-m.width/2-padX,-size/2-padY,m.width+padX*2,size+padY*2,9);ctx.fill()}ctx.fillStyle=o.dataset.bg?(o.dataset.bg==='#000'?'#fff':'#000'):(o.dataset.color||'#fff');if(o.dataset.shadow!=='false'){ctx.shadowColor='rgba(0,0,0,.55)';ctx.shadowBlur=5}ctx.fillText(o.textContent,0,0)}else{ctx.globalAlpha=1;ctx.font='48px sans-serif';ctx.fillText(o.textContent,0,0)}ctx.restore()}
ctx.globalAlpha=1;ctx.filter='none';ctx.fillStyle='#fff';ctx.fillRect(0,outH,outW,footer);ctx.fillStyle='#111';ctx.font=`700 ${Math.max(18,Math.min(34,Math.round(outW*.011)))}px -apple-system,BlinkMacSystemFont,"SF Pro Display",sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('made with intensed-dev.github.io/paperplane',outW/2,outH+footer/2);toastMsg('Exporting…');canvas.toBlob(blob=>{if(!blob)return toastMsg('Export failed');const a=document.createElement('a');a.download='paperplane.png';a.href=URL.createObjectURL(blob);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);toastMsg('Saved to your device')},'image/png')}
$('#download').onclick=exportImage;
